language: node_js

env:
     - DATABASE_URL=postgresql://postgres@localhost:5432/waiter-app

node_js:
  - "v8.9.4"

before_script:
  - psql -c 'create database  waiter-app;' -U postgres
  - psql -U postgres -d waiter-app -a -f database.sql
  
addons:
    apt:
    packages:
    - postgresql-server-dev-9.2